# Generated by Django 3.1.6 on 2021-02-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('duration', models.IntegerField()),
                ('fees', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('father_firstname', models.CharField(max_length=50)),
                ('father_secondname', models.CharField(max_length=50)),
                ('father_lastname', models.CharField(max_length=50)),
                ('Building_name', models.CharField(max_length=50)),
                ('state_name', models.CharField(max_length=50)),
                ('area_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('ph_number', models.IntegerField()),
                ('ph_number_house', models.IntegerField()),
                ('birthdate', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('Schoolname', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='Profile Pic')),
                ('email', models.CharField(max_length=50)),
                ('inquiry_id', models.CharField(max_length=50)),
            ],
        ),
    ]
