# Generated by Django 3.1.6 on 2021-02-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses_master',
            name='desc',
            field=models.TextField(),
        ),
    ]
