# Generated by Django 3.1.6 on 2021-02-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_addmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='ph_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='student',
            name='ph_number_house',
            field=models.CharField(max_length=11),
        ),
    ]
