# Generated by Django 3.1.6 on 2021-02-21 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmission',
            name='payment',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='addmission', to='courses.payment'),
        ),
    ]
