# Generated by Django 3.1.6 on 2021-02-25 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210225_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('presence', models.CharField(choices=[('Yes', 'Present'), ('No', 'Absent')], max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=50)),
                ('time', models.TimeField()),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='courses.addmission')),
            ],
        ),
    ]
