# Generated by Django 3.1.6 on 2021-02-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='courses_master',
            name='duration',
            field=models.DateTimeField(),
        ),
    ]
