# Generated by Django 3.1.6 on 2021-02-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20210227_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses_master',
            name='duration',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='courses_master',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50),
        ),
    ]
