# Generated by Django 3.1.6 on 2021-02-27 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_timetable_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmission',
            name='time_table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_table', to='courses.timetable'),
        ),
    ]
